export type CostLevel = 'budget' | 'mid' | 'premium';

export type Destination = {
  city: string;
  country: string;
  flag: string;
  airportCode: string;
  hotelNightEstimate: number;
  foodPerDay: number;
  transportPerDay: number;
  activityPerDay: number;
  costLevel: CostLevel;
  description: string;
};

export type Theme = {
  id: string;
  icon: string;
  name: string;
  desc: string;
  destinations: Destination[];
};

export const themes: Theme[] = [
  {
    id: 'beach',
    icon: '🏖️',
    name: 'Sun & Beach',
    desc: 'Sand, sea & relaxation',
    destinations: [
      {
        city: 'Málaga',
        country: 'Spain',
        flag: 'es',
        airportCode: 'AGP',
        hotelNightEstimate: 65,
        foodPerDay: 40,
        transportPerDay: 15,
        activityPerDay: 25,
        costLevel: 'budget',
        description: 'Sunny Costa del Sol with great beaches and tapas',
      },
      {
        city: 'Mallorca',
        country: 'Spain',
        flag: 'es',
        airportCode: 'PMI',
        hotelNightEstimate: 80,
        foodPerDay: 45,
        transportPerDay: 15,
        activityPerDay: 30,
        costLevel: 'budget',
        description: 'Stunning coves and lively resorts',
      },
      {
        city: 'Santorini',
        country: 'Greece',
        flag: 'gr',
        airportCode: 'JTR',
        hotelNightEstimate: 160,
        foodPerDay: 60,
        transportPerDay: 20,
        activityPerDay: 40,
        costLevel: 'premium',
        description: 'Iconic white cliffs and volcanic beaches',
      },
      {
        city: 'Nice',
        country: 'France',
        flag: 'fr',
        airportCode: 'NCE',
        hotelNightEstimate: 110,
        foodPerDay: 65,
        transportPerDay: 20,
        activityPerDay: 35,
        costLevel: 'mid',
        description: 'French Riviera glamour and pebbly beaches',
      },
      {
        city: 'Algarve',
        country: 'Portugal',
        flag: 'pt',
        airportCode: 'FAO',
        hotelNightEstimate: 75,
        foodPerDay: 40,
        transportPerDay: 18,
        activityPerDay: 25,
        costLevel: 'budget',
        description: 'Golden cliffs and turquoise Atlantic waters',
      },
      {
        city: 'Mykonos',
        country: 'Greece',
        flag: 'gr',
        airportCode: 'JMK',
        hotelNightEstimate: 180,
        foodPerDay: 70,
        transportPerDay: 20,
        activityPerDay: 50,
        costLevel: 'premium',
        description: 'Cosmopolitan island with world-class beaches',
      },
      {
        city: 'Split',
        country: 'Croatia',
        flag: 'hr',
        airportCode: 'SPU',
        hotelNightEstimate: 70,
        foodPerDay: 38,
        transportPerDay: 14,
        activityPerDay: 28,
        costLevel: 'budget',
        description: 'Adriatic coastline with ancient old town',
      },
      {
        city: 'Tenerife',
        country: 'Spain',
        flag: 'es',
        airportCode: 'TFS',
        hotelNightEstimate: 72,
        foodPerDay: 42,
        transportPerDay: 15,
        activityPerDay: 28,
        costLevel: 'budget',
        description: 'Year-round sunshine and volcanic landscapes',
      },
      {
        city: 'Dubrovnik',
        country: 'Croatia',
        flag: 'hr',
        airportCode: 'DBV',
        hotelNightEstimate: 100,
        foodPerDay: 50,
        transportPerDay: 16,
        activityPerDay: 35,
        costLevel: 'mid',
        description: 'The Pearl of the Adriatic, crystal-clear sea',
      },
      {
        city: 'Corsica',
        country: 'France',
        flag: 'fr',
        airportCode: 'AJA',
        hotelNightEstimate: 95,
        foodPerDay: 55,
        transportPerDay: 20,
        activityPerDay: 30,
        costLevel: 'mid',
        description: 'Wild mountains meet turquoise lagoons',
      },
      {
        city: 'Bali',
        country: 'Indonesia',
        flag: 'id',
        airportCode: 'DPS',
        hotelNightEstimate: 45,
        foodPerDay: 20,
        transportPerDay: 12,
        activityPerDay: 25,
        costLevel: 'budget',
        description: 'Tropical paradise with temples, rice fields and surf',
      },
      {
        city: 'Phuket',
        country: 'Thailand',
        flag: 'th',
        airportCode: 'HKT',
        hotelNightEstimate: 55,
        foodPerDay: 22,
        transportPerDay: 12,
        activityPerDay: 28,
        costLevel: 'budget',
        description: 'Stunning beaches, clear waters and vibrant nightlife',
      },
      {
        city: 'Maldives',
        country: 'Maldives',
        flag: 'mv',
        airportCode: 'MLE',
        hotelNightEstimate: 350,
        foodPerDay: 100,
        transportPerDay: 40,
        activityPerDay: 80,
        costLevel: 'premium',
        description: 'Overwater bungalows and the clearest water on earth',
      },
      {
        city: 'Zanzibar',
        country: 'Tanzania',
        flag: 'tz',
        airportCode: 'ZNZ',
        hotelNightEstimate: 80,
        foodPerDay: 30,
        transportPerDay: 15,
        activityPerDay: 35,
        costLevel: 'mid',
        description: 'Spice island with white sand beaches and Swahili culture',
      },
      {
        city: 'Krabi',
        country: 'Thailand',
        flag: 'th',
        airportCode: 'KBV',
        hotelNightEstimate: 45,
        foodPerDay: 18,
        transportPerDay: 12,
        activityPerDay: 30,
        costLevel: 'budget',
        description: 'Dramatic limestone cliffs and emerald green lagoons',
      },
      {
        city: 'Boracay',
        country: 'Philippines',
        flag: 'ph',
        airportCode: 'MPH',
        hotelNightEstimate: 60,
        foodPerDay: 22,
        transportPerDay: 10,
        activityPerDay: 28,
        costLevel: 'budget',
        description: 'Powdery white sand and world-famous sunsets',
      },
      {
        city: 'Mauritius',
        country: 'Mauritius',
        flag: 'mu',
        airportCode: 'MRU',
        hotelNightEstimate: 140,
        foodPerDay: 55,
        transportPerDay: 25,
        activityPerDay: 45,
        costLevel: 'premium',
        description: 'Luxury island with lagoons, reefs and colonial charm',
      },
      {
        city: 'Da Nang',
        country: 'Vietnam',
        flag: 'vn',
        airportCode: 'DAD',
        hotelNightEstimate: 40,
        foodPerDay: 18,
        transportPerDay: 10,
        activityPerDay: 20,
        costLevel: 'budget',
        description: 'Long sandy beaches with ancient Hoi An nearby',
      },
      {
        city: 'Cancún',
        country: 'Mexico',
        flag: 'mx',
        airportCode: 'CUN',
        hotelNightEstimate: 90,
        foodPerDay: 35,
        transportPerDay: 15,
        activityPerDay: 40,
        costLevel: 'mid',
        description: 'Caribbean turquoise waters and Mayan ruins nearby',
      },
      {
        city: 'Cape Verde',
        country: 'Cape Verde',
        flag: 'cv',
        airportCode: 'SID',
        hotelNightEstimate: 70,
        foodPerDay: 30,
        transportPerDay: 14,
        activityPerDay: 25,
        costLevel: 'budget',
        description: 'Atlantic island paradise with year-round warm winds',
      },
    ],
  },
  {
    id: 'city',
    icon: '🏙️',
    name: 'City Break',
    desc: 'Culture, food & nightlife',
    destinations: [
      {
        city: 'Barcelona',
        country: 'Spain',
        flag: 'es',
        airportCode: 'BCN',
        hotelNightEstimate: 90,
        foodPerDay: 50,
        transportPerDay: 15,
        activityPerDay: 35,
        costLevel: 'mid',
        description: 'Gaudí architecture, beaches and amazing food',
      },
      {
        city: 'Amsterdam',
        country: 'Netherlands',
        flag: 'nl',
        airportCode: 'AMS',
        hotelNightEstimate: 115,
        foodPerDay: 55,
        transportPerDay: 20,
        activityPerDay: 40,
        costLevel: 'mid',
        description: 'Canals, museums and vibrant nightlife',
      },
      {
        city: 'Lisbon',
        country: 'Portugal',
        flag: 'pt',
        airportCode: 'LIS',
        hotelNightEstimate: 75,
        foodPerDay: 40,
        transportPerDay: 12,
        activityPerDay: 25,
        costLevel: 'budget',
        description: 'Hilly streets, trams and incredible seafood',
      },
      {
        city: 'Vienna',
        country: 'Austria',
        flag: 'at',
        airportCode: 'VIE',
        hotelNightEstimate: 100,
        foodPerDay: 55,
        transportPerDay: 18,
        activityPerDay: 45,
        costLevel: 'mid',
        description: 'Imperial grandeur, coffee houses and opera',
      },
      {
        city: 'Copenhagen',
        country: 'Denmark',
        flag: 'dk',
        airportCode: 'CPH',
        hotelNightEstimate: 120,
        foodPerDay: 70,
        transportPerDay: 20,
        activityPerDay: 45,
        costLevel: 'mid',
        description: 'Design capital with world-class restaurants',
      },
      {
        city: 'Berlin',
        country: 'Germany',
        flag: 'de',
        airportCode: 'BER',
        hotelNightEstimate: 85,
        foodPerDay: 45,
        transportPerDay: 15,
        activityPerDay: 35,
        costLevel: 'budget',
        description: 'Art, history and legendary nightlife',
      },
      {
        city: 'Paris',
        country: 'France',
        flag: 'fr',
        airportCode: 'CDG',
        hotelNightEstimate: 130,
        foodPerDay: 70,
        transportPerDay: 20,
        activityPerDay: 50,
        costLevel: 'premium',
        description: 'The city of light — fashion, art and cuisine',
      },
      {
        city: 'London',
        country: 'UK',
        flag: 'gb',
        airportCode: 'LHR',
        hotelNightEstimate: 140,
        foodPerDay: 75,
        transportPerDay: 25,
        activityPerDay: 55,
        costLevel: 'premium',
        description: 'World-class museums, theatre and food scene',
      },
      {
        city: 'Madrid',
        country: 'Spain',
        flag: 'es',
        airportCode: 'MAD',
        hotelNightEstimate: 85,
        foodPerDay: 48,
        transportPerDay: 14,
        activityPerDay: 35,
        costLevel: 'mid',
        description: 'Passionate city with great art and nightlife',
      },
      {
        city: 'Budapest',
        country: 'Hungary',
        flag: 'hu',
        airportCode: 'BUD',
        hotelNightEstimate: 60,
        foodPerDay: 32,
        transportPerDay: 10,
        activityPerDay: 25,
        costLevel: 'budget',
        description: 'Thermal baths, ruin bars and the Danube',
      },
      {
        city: 'Tokyo',
        country: 'Japan',
        flag: 'jp',
        airportCode: 'NRT',
        hotelNightEstimate: 110,
        foodPerDay: 45,
        transportPerDay: 20,
        activityPerDay: 40,
        costLevel: 'mid',
        description: 'Neon-lit megacity blending ancient temples and futurism',
      },
      {
        city: 'Singapore',
        country: 'Singapore',
        flag: 'sg',
        airportCode: 'SIN',
        hotelNightEstimate: 130,
        foodPerDay: 40,
        transportPerDay: 15,
        activityPerDay: 45,
        costLevel: 'premium',
        description:
          'Ultramodern city-state with incredible food hawker centres',
      },
      {
        city: 'Bangkok',
        country: 'Thailand',
        flag: 'th',
        airportCode: 'BKK',
        hotelNightEstimate: 45,
        foodPerDay: 18,
        transportPerDay: 10,
        activityPerDay: 25,
        costLevel: 'budget',
        description:
          'Chaotic, colourful city of temples, markets and street food',
      },
      {
        city: 'Dubai',
        country: 'UAE',
        flag: 'ae',
        airportCode: 'DXB',
        hotelNightEstimate: 150,
        foodPerDay: 65,
        transportPerDay: 25,
        activityPerDay: 60,
        costLevel: 'premium',
        description:
          'Futuristic skyline, luxury shopping and desert adventures',
      },
      {
        city: 'Hong Kong',
        country: 'Hong Kong',
        flag: 'hk',
        airportCode: 'HKG',
        hotelNightEstimate: 120,
        foodPerDay: 40,
        transportPerDay: 12,
        activityPerDay: 40,
        costLevel: 'mid',
        description: 'Skyscrapers, dim sum and dramatic harbour views',
      },
      {
        city: 'Marrakech',
        country: 'Morocco',
        flag: 'ma',
        airportCode: 'RAK',
        hotelNightEstimate: 55,
        foodPerDay: 22,
        transportPerDay: 12,
        activityPerDay: 25,
        costLevel: 'budget',
        description: 'Maze-like medina, souks and rooftop terraces',
      },
      {
        city: 'Mexico City',
        country: 'Mexico',
        flag: 'mx',
        airportCode: 'MEX',
        hotelNightEstimate: 60,
        foodPerDay: 25,
        transportPerDay: 10,
        activityPerDay: 30,
        costLevel: 'budget',
        description: 'Vibrant megacity with world-class museums and food',
      },
      {
        city: 'Kyoto',
        country: 'Japan',
        flag: 'jp',
        airportCode: 'ITM',
        hotelNightEstimate: 100,
        foodPerDay: 40,
        transportPerDay: 15,
        activityPerDay: 35,
        costLevel: 'mid',
        description: 'Ancient temples, geisha districts and bamboo forests',
      },
      {
        city: 'Buenos Aires',
        country: 'Argentina',
        flag: 'ar',
        airportCode: 'EZE',
        hotelNightEstimate: 55,
        foodPerDay: 25,
        transportPerDay: 8,
        activityPerDay: 25,
        costLevel: 'budget',
        description: 'Paris of South America — tango, steak and passion',
      },
      {
        city: 'Cape Town',
        country: 'South Africa',
        flag: 'za',
        airportCode: 'CPT',
        hotelNightEstimate: 70,
        foodPerDay: 30,
        transportPerDay: 18,
        activityPerDay: 40,
        costLevel: 'mid',
        description:
          "Mountain, ocean and wine — one of the world's great cities",
      },
    ],
  },
  {
    id: 'nature',
    icon: '🏔️',
    name: 'Nature & Hiking',
    desc: 'Landscapes & fresh air',
    destinations: [
      {
        city: 'Reykjavik',
        country: 'Iceland',
        flag: 'is',
        airportCode: 'KEF',
        hotelNightEstimate: 140,
        foodPerDay: 70,
        transportPerDay: 50,
        activityPerDay: 80,
        costLevel: 'premium',
        description: 'Volcanoes, geysers and the Northern Lights',
      },
      {
        city: 'Interlaken',
        country: 'Switzerland',
        flag: 'ch',
        airportCode: 'ZRH',
        hotelNightEstimate: 130,
        foodPerDay: 75,
        transportPerDay: 30,
        activityPerDay: 90,
        costLevel: 'premium',
        description: 'Between two lakes, surrounded by the Alps',
      },
      {
        city: 'Tromsø',
        country: 'Norway',
        flag: 'no',
        airportCode: 'TOS',
        hotelNightEstimate: 120,
        foodPerDay: 80,
        transportPerDay: 25,
        activityPerDay: 70,
        costLevel: 'premium',
        description: 'Arctic wilderness and aurora borealis',
      },
      {
        city: 'Ljubljana',
        country: 'Slovenia',
        flag: 'si',
        airportCode: 'LJU',
        hotelNightEstimate: 70,
        foodPerDay: 40,
        transportPerDay: 15,
        activityPerDay: 30,
        costLevel: 'budget',
        description: 'Gateway to Triglav and Lake Bled',
      },
      {
        city: 'Innsbruck',
        country: 'Austria',
        flag: 'at',
        airportCode: 'INN',
        hotelNightEstimate: 95,
        foodPerDay: 55,
        transportPerDay: 20,
        activityPerDay: 60,
        costLevel: 'mid',
        description: 'Alpine city with skiing and stunning hikes',
      },
      {
        city: 'Bergen',
        country: 'Norway',
        flag: 'no',
        airportCode: 'BGO',
        hotelNightEstimate: 110,
        foodPerDay: 75,
        transportPerDay: 22,
        activityPerDay: 55,
        costLevel: 'premium',
        description: 'Gateway to the fjords, colourful wooden houses',
      },
      {
        city: 'Zakopane',
        country: 'Poland',
        flag: 'pl',
        airportCode: 'KRK',
        hotelNightEstimate: 50,
        foodPerDay: 28,
        transportPerDay: 12,
        activityPerDay: 30,
        costLevel: 'budget',
        description: 'The winter capital at the foot of the Tatras',
      },
      {
        city: 'Queenstown',
        country: 'New Zealand',
        flag: 'nz',
        airportCode: 'ZQN',
        hotelNightEstimate: 130,
        foodPerDay: 65,
        transportPerDay: 35,
        activityPerDay: 110,
        costLevel: 'premium',
        description: 'Adventure capital set on a glacial lake',
      },
      {
        city: 'Madeira',
        country: 'Portugal',
        flag: 'pt',
        airportCode: 'FNC',
        hotelNightEstimate: 75,
        foodPerDay: 40,
        transportPerDay: 18,
        activityPerDay: 35,
        costLevel: 'budget',
        description: 'Levada walks through lush volcanic scenery',
      },
      {
        city: 'Chamonix',
        country: 'France',
        flag: 'fr',
        airportCode: 'GVA',
        hotelNightEstimate: 130,
        foodPerDay: 70,
        transportPerDay: 25,
        activityPerDay: 80,
        costLevel: 'premium',
        description: 'At the foot of Mont Blanc — legendary trails',
      },
      {
        city: 'Kathmandu',
        country: 'Nepal',
        flag: 'np',
        airportCode: 'KTM',
        hotelNightEstimate: 30,
        foodPerDay: 15,
        transportPerDay: 10,
        activityPerDay: 40,
        costLevel: 'budget',
        description: 'Gateway to Everest and the Himalayas',
      },
      {
        city: 'Patagonia',
        country: 'Chile',
        flag: 'cl',
        airportCode: 'PUQ',
        hotelNightEstimate: 90,
        foodPerDay: 40,
        transportPerDay: 35,
        activityPerDay: 70,
        costLevel: 'mid',
        description: 'End of the world glaciers, peaks and wild winds',
      },
      {
        city: 'Banff',
        country: 'Canada',
        flag: 'ca',
        airportCode: 'YYC',
        hotelNightEstimate: 120,
        foodPerDay: 55,
        transportPerDay: 30,
        activityPerDay: 65,
        costLevel: 'premium',
        description: 'Turquoise lakes and Rocky Mountain grandeur',
      },
      {
        city: 'Guilin',
        country: 'China',
        flag: 'cn',
        airportCode: 'KWL',
        hotelNightEstimate: 45,
        foodPerDay: 18,
        transportPerDay: 12,
        activityPerDay: 30,
        costLevel: 'budget',
        description: 'Dramatic karst mountains rising from rice paddies',
      },
      {
        city: 'Yosemite',
        country: 'USA',
        flag: 'us',
        airportCode: 'SFO',
        hotelNightEstimate: 110,
        foodPerDay: 55,
        transportPerDay: 30,
        activityPerDay: 45,
        costLevel: 'mid',
        description: 'Giant sequoias, waterfalls and granite cliffs',
      },
      {
        city: 'Cappadocia',
        country: 'Turkey',
        flag: 'tr',
        airportCode: 'ASR',
        hotelNightEstimate: 70,
        foodPerDay: 25,
        transportPerDay: 15,
        activityPerDay: 60,
        costLevel: 'mid',
        description: 'Fairy chimneys, hot air balloons and cave hotels',
      },
      {
        city: 'Fiordland',
        country: 'New Zealand',
        flag: 'nz',
        airportCode: 'ZQN',
        hotelNightEstimate: 110,
        foodPerDay: 55,
        transportPerDay: 30,
        activityPerDay: 70,
        costLevel: 'premium',
        description: 'Milford Sound and untouched wilderness',
      },
      {
        city: 'Costa Rica',
        country: 'Costa Rica',
        flag: 'cr',
        airportCode: 'SJO',
        hotelNightEstimate: 65,
        foodPerDay: 28,
        transportPerDay: 20,
        activityPerDay: 55,
        costLevel: 'mid',
        description: 'Rainforests, volcanoes and incredible biodiversity',
      },
      {
        city: 'Zhangjiajie',
        country: 'China',
        flag: 'cn',
        airportCode: 'DYG',
        hotelNightEstimate: 40,
        foodPerDay: 15,
        transportPerDay: 12,
        activityPerDay: 30,
        costLevel: 'budget',
        description: 'Avatar-like floating mountains and glass bridges',
      },
      {
        city: 'Kilimanjaro',
        country: 'Tanzania',
        flag: 'tz',
        airportCode: 'JRO',
        hotelNightEstimate: 60,
        foodPerDay: 25,
        transportPerDay: 20,
        activityPerDay: 90,
        costLevel: 'mid',
        description: "Africa's highest peak and safari country",
      },
    ],
  },
  {
    id: 'culture',
    icon: '🏛️',
    name: 'History & Culture',
    desc: 'Museums & old towns',
    destinations: [
      {
        city: 'Rome',
        country: 'Italy',
        flag: 'it',
        airportCode: 'FCO',
        hotelNightEstimate: 100,
        foodPerDay: 55,
        transportPerDay: 15,
        activityPerDay: 45,
        costLevel: 'mid',
        description: 'The Eternal City — Colosseum, Vatican, gelato',
      },
      {
        city: 'Athens',
        country: 'Greece',
        flag: 'gr',
        airportCode: 'ATH',
        hotelNightEstimate: 75,
        foodPerDay: 40,
        transportPerDay: 12,
        activityPerDay: 35,
        costLevel: 'budget',
        description: 'The cradle of Western civilisation',
      },
      {
        city: 'Prague',
        country: 'Czech Republic',
        flag: 'cz',
        airportCode: 'PRG',
        hotelNightEstimate: 70,
        foodPerDay: 35,
        transportPerDay: 10,
        activityPerDay: 30,
        costLevel: 'budget',
        description: 'Fairy-tale old town and gothic architecture',
      },
      {
        city: 'Istanbul',
        country: 'Turkey',
        flag: 'tr',
        airportCode: 'IST',
        hotelNightEstimate: 65,
        foodPerDay: 30,
        transportPerDay: 10,
        activityPerDay: 25,
        costLevel: 'budget',
        description: 'Where East meets West — mosques and bazaars',
      },
      {
        city: 'Florence',
        country: 'Italy',
        flag: 'it',
        airportCode: 'FLR',
        hotelNightEstimate: 105,
        foodPerDay: 58,
        transportPerDay: 12,
        activityPerDay: 50,
        costLevel: 'mid',
        description: 'Renaissance art capital — Uffizi and Duomo',
      },
      {
        city: 'Krakow',
        country: 'Poland',
        flag: 'pl',
        airportCode: 'KRK',
        hotelNightEstimate: 55,
        foodPerDay: 28,
        transportPerDay: 8,
        activityPerDay: 25,
        costLevel: 'budget',
        description: 'Medieval old town and rich Jewish heritage',
      },
      {
        city: 'Seville',
        country: 'Spain',
        flag: 'es',
        airportCode: 'SVQ',
        hotelNightEstimate: 80,
        foodPerDay: 42,
        transportPerDay: 12,
        activityPerDay: 30,
        costLevel: 'budget',
        description: 'Flamenco, tapas and Moorish architecture',
      },
      {
        city: 'Bruges',
        country: 'Belgium',
        flag: 'be',
        airportCode: 'BRU',
        hotelNightEstimate: 95,
        foodPerDay: 52,
        transportPerDay: 10,
        activityPerDay: 30,
        costLevel: 'mid',
        description: 'Medieval canals and world-famous chocolate',
      },
      {
        city: 'Tallinn',
        country: 'Estonia',
        flag: 'ee',
        airportCode: 'TLL',
        hotelNightEstimate: 60,
        foodPerDay: 32,
        transportPerDay: 10,
        activityPerDay: 25,
        costLevel: 'budget',
        description: 'Best-preserved medieval old town in Europe',
      },
      {
        city: 'Dubrovnik',
        country: 'Croatia',
        flag: 'hr',
        airportCode: 'DBV',
        hotelNightEstimate: 100,
        foodPerDay: 50,
        transportPerDay: 15,
        activityPerDay: 40,
        costLevel: 'mid',
        description:
          'Walled city on the Adriatic — Game of Thrones filming location',
      },
      {
        city: 'Kyoto',
        country: 'Japan',
        flag: 'jp',
        airportCode: 'ITM',
        hotelNightEstimate: 100,
        foodPerDay: 40,
        transportPerDay: 15,
        activityPerDay: 35,
        costLevel: 'mid',
        description: 'Ancient temples, geisha districts and bamboo forests',
      },
      {
        city: 'Petra',
        country: 'Jordan',
        flag: 'jo',
        airportCode: 'AMM',
        hotelNightEstimate: 70,
        foodPerDay: 28,
        transportPerDay: 15,
        activityPerDay: 45,
        costLevel: 'mid',
        description: 'The rose-red city carved into desert cliffs',
      },
      {
        city: 'Marrakech',
        country: 'Morocco',
        flag: 'ma',
        airportCode: 'RAK',
        hotelNightEstimate: 55,
        foodPerDay: 22,
        transportPerDay: 12,
        activityPerDay: 25,
        costLevel: 'budget',
        description: 'Maze-like medina, souks and rooftop terraces',
      },
      {
        city: 'Cairo',
        country: 'Egypt',
        flag: 'eg',
        airportCode: 'CAI',
        hotelNightEstimate: 50,
        foodPerDay: 20,
        transportPerDay: 12,
        activityPerDay: 35,
        costLevel: 'budget',
        description: 'Pyramids of Giza and 5,000 years of history',
      },
      {
        city: 'Varanasi',
        country: 'India',
        flag: 'in',
        airportCode: 'VNS',
        hotelNightEstimate: 25,
        foodPerDay: 12,
        transportPerDay: 8,
        activityPerDay: 20,
        costLevel: 'budget',
        description:
          'The holiest city on the Ganges — ancient and overwhelming',
      },
      {
        city: 'Angkor Wat',
        country: 'Cambodia',
        flag: 'kh',
        airportCode: 'REP',
        hotelNightEstimate: 35,
        foodPerDay: 15,
        transportPerDay: 10,
        activityPerDay: 25,
        costLevel: 'budget',
        description: 'The largest religious monument in the world',
      },
      {
        city: 'Cusco',
        country: 'Peru',
        flag: 'pe',
        airportCode: 'CUZ',
        hotelNightEstimate: 45,
        foodPerDay: 20,
        transportPerDay: 10,
        activityPerDay: 40,
        costLevel: 'budget',
        description: 'Inca empire capital and gateway to Machu Picchu',
      },
      {
        city: 'Fez',
        country: 'Morocco',
        flag: 'ma',
        airportCode: 'FEZ',
        hotelNightEstimate: 45,
        foodPerDay: 18,
        transportPerDay: 10,
        activityPerDay: 20,
        costLevel: 'budget',
        description:
          "The world's largest car-free urban area and medieval medina",
      },
      {
        city: 'Samarkand',
        country: 'Uzbekistan',
        flag: 'uz',
        airportCode: 'SKD',
        hotelNightEstimate: 35,
        foodPerDay: 15,
        transportPerDay: 8,
        activityPerDay: 20,
        costLevel: 'budget',
        description: 'Silk Road jewel with breathtaking Islamic architecture',
      },
      {
        city: 'Havana',
        country: 'Cuba',
        flag: 'cu',
        airportCode: 'HAV',
        hotelNightEstimate: 55,
        foodPerDay: 25,
        transportPerDay: 12,
        activityPerDay: 25,
        costLevel: 'budget',
        description:
          'Frozen in time — vintage cars, salsa and colonial grandeur',
      },
    ],
  },
  {
    id: 'food',
    icon: '🍷',
    name: 'Food & Wine',
    desc: 'Gastronomy & markets',
    destinations: [
      {
        city: 'San Sebastián',
        country: 'Spain',
        flag: 'es',
        airportCode: 'EAS',
        hotelNightEstimate: 110,
        foodPerDay: 80,
        transportPerDay: 15,
        activityPerDay: 30,
        costLevel: 'mid',
        description: 'Most Michelin stars per capita in the world',
      },
      {
        city: 'Bologna',
        country: 'Italy',
        flag: 'it',
        airportCode: 'BLQ',
        hotelNightEstimate: 85,
        foodPerDay: 65,
        transportPerDay: 12,
        activityPerDay: 25,
        costLevel: 'mid',
        description: 'La Grassa — birthplace of pasta and ragù',
      },
      {
        city: 'Lyon',
        country: 'France',
        flag: 'fr',
        airportCode: 'LYS',
        hotelNightEstimate: 95,
        foodPerDay: 70,
        transportPerDay: 15,
        activityPerDay: 30,
        costLevel: 'mid',
        description: 'The gastronomic capital of France',
      },
      {
        city: 'Porto',
        country: 'Portugal',
        flag: 'pt',
        airportCode: 'OPO',
        hotelNightEstimate: 70,
        foodPerDay: 45,
        transportPerDay: 12,
        activityPerDay: 20,
        costLevel: 'budget',
        description: 'Port wine, pastéis de nata and seafood',
      },
      {
        city: 'Naples',
        country: 'Italy',
        flag: 'it',
        airportCode: 'NAP',
        hotelNightEstimate: 70,
        foodPerDay: 45,
        transportPerDay: 12,
        activityPerDay: 25,
        costLevel: 'budget',
        description: 'Birthplace of pizza and home of street food',
      },
      {
        city: 'Bordeaux',
        country: 'France',
        flag: 'fr',
        airportCode: 'BOD',
        hotelNightEstimate: 90,
        foodPerDay: 65,
        transportPerDay: 14,
        activityPerDay: 35,
        costLevel: 'mid',
        description: 'Wine capital of the world — châteaux and caves',
      },
      {
        city: 'Copenhagen',
        country: 'Denmark',
        flag: 'dk',
        airportCode: 'CPH',
        hotelNightEstimate: 125,
        foodPerDay: 80,
        transportPerDay: 20,
        activityPerDay: 45,
        costLevel: 'premium',
        description: 'New Nordic cuisine — Noma changed everything',
      },
      {
        city: 'Palermo',
        country: 'Italy',
        flag: 'it',
        airportCode: 'PMO',
        hotelNightEstimate: 65,
        foodPerDay: 38,
        transportPerDay: 10,
        activityPerDay: 20,
        costLevel: 'budget',
        description: 'Street food paradise — arancini and sfincione',
      },
      {
        city: 'Tbilisi',
        country: 'Georgia',
        flag: 'ge',
        airportCode: 'TBS',
        hotelNightEstimate: 50,
        foodPerDay: 30,
        transportPerDay: 8,
        activityPerDay: 20,
        costLevel: 'budget',
        description: 'Ancient wine culture and unforgettable khinkali',
      },
      {
        city: 'Thessaloniki',
        country: 'Greece',
        flag: 'gr',
        airportCode: 'SKG',
        hotelNightEstimate: 65,
        foodPerDay: 40,
        transportPerDay: 10,
        activityPerDay: 22,
        costLevel: 'budget',
        description: 'The food capital of Greece — bougatsa to souvlaki',
      },
      {
        city: 'Tokyo',
        country: 'Japan',
        flag: 'jp',
        airportCode: 'NRT',
        hotelNightEstimate: 110,
        foodPerDay: 45,
        transportPerDay: 20,
        activityPerDay: 35,
        costLevel: 'mid',
        description: 'Most Michelin-starred city in the world — ramen to sushi',
      },
      {
        city: 'Bangkok',
        country: 'Thailand',
        flag: 'th',
        airportCode: 'BKK',
        hotelNightEstimate: 45,
        foodPerDay: 18,
        transportPerDay: 10,
        activityPerDay: 20,
        costLevel: 'budget',
        description:
          'Street food paradise — pad thai, mango sticky rice and more',
      },
      {
        city: 'Ho Chi Minh City',
        country: 'Vietnam',
        flag: 'vn',
        airportCode: 'SGN',
        hotelNightEstimate: 35,
        foodPerDay: 15,
        transportPerDay: 8,
        activityPerDay: 18,
        costLevel: 'budget',
        description: 'Pho, banh mi and vibrant street food culture',
      },
      {
        city: 'Mexico City',
        country: 'Mexico',
        flag: 'mx',
        airportCode: 'MEX',
        hotelNightEstimate: 60,
        foodPerDay: 25,
        transportPerDay: 10,
        activityPerDay: 25,
        costLevel: 'budget',
        description: "Tacos, mole and some of the world's best new restaurants",
      },
      {
        city: 'Singapore',
        country: 'Singapore',
        flag: 'sg',
        airportCode: 'SIN',
        hotelNightEstimate: 130,
        foodPerDay: 40,
        transportPerDay: 15,
        activityPerDay: 30,
        costLevel: 'premium',
        description: "Hawker centres to fine dining — Asia's food crossroads",
      },
      {
        city: 'Osaka',
        country: 'Japan',
        flag: 'jp',
        airportCode: 'KIX',
        hotelNightEstimate: 90,
        foodPerDay: 40,
        transportPerDay: 15,
        activityPerDay: 30,
        costLevel: 'mid',
        description: "Japan's kitchen — takoyaki, okonomiyaki and ramen",
      },
      {
        city: 'Lima',
        country: 'Peru',
        flag: 'pe',
        airportCode: 'LIM',
        hotelNightEstimate: 55,
        foodPerDay: 28,
        transportPerDay: 12,
        activityPerDay: 25,
        costLevel: 'budget',
        description: "Ceviche capital and home of the world's best restaurants",
      },
      {
        city: 'Cape Town',
        country: 'South Africa',
        flag: 'za',
        airportCode: 'CPT',
        hotelNightEstimate: 70,
        foodPerDay: 30,
        transportPerDay: 18,
        activityPerDay: 35,
        costLevel: 'mid',
        description: 'World-class wine region and a booming restaurant scene',
      },
      {
        city: 'Istanbul',
        country: 'Turkey',
        flag: 'tr',
        airportCode: 'IST',
        hotelNightEstimate: 65,
        foodPerDay: 30,
        transportPerDay: 10,
        activityPerDay: 20,
        costLevel: 'budget',
        description: 'Kebabs, mezze, baklava and the grand bazaar',
      },
      {
        city: 'Chiang Mai',
        country: 'Thailand',
        flag: 'th',
        airportCode: 'CNX',
        hotelNightEstimate: 35,
        foodPerDay: 15,
        transportPerDay: 8,
        activityPerDay: 20,
        costLevel: 'budget',
        description: 'Cooking classes, night markets and Northern Thai cuisine',
      },
    ],
  },
  {
    id: 'adventure',
    icon: '🧗',
    name: 'Adventure',
    desc: 'Sports & adrenaline',
    destinations: [
      {
        city: 'Queenstown',
        country: 'New Zealand',
        flag: 'nz',
        airportCode: 'ZQN',
        hotelNightEstimate: 120,
        foodPerDay: 60,
        transportPerDay: 30,
        activityPerDay: 120,
        costLevel: 'premium',
        description: 'Bungee, skydive, jet boat — the adventure capital',
      },
      {
        city: 'Chamonix',
        country: 'France',
        flag: 'fr',
        airportCode: 'GVA',
        hotelNightEstimate: 130,
        foodPerDay: 70,
        transportPerDay: 25,
        activityPerDay: 80,
        costLevel: 'premium',
        description: 'Skiing and mountaineering under Mont Blanc',
      },
      {
        city: 'Kotor',
        country: 'Montenegro',
        flag: 'me',
        airportCode: 'TIV',
        hotelNightEstimate: 60,
        foodPerDay: 35,
        transportPerDay: 15,
        activityPerDay: 40,
        costLevel: 'budget',
        description: 'Kayaking, hiking and cliff diving on the bay',
      },
      {
        city: 'Moab',
        country: 'USA',
        flag: 'us',
        airportCode: 'CNY',
        hotelNightEstimate: 100,
        foodPerDay: 55,
        transportPerDay: 40,
        activityPerDay: 90,
        costLevel: 'mid',
        description: 'Red rock canyons, mountain biking and rafting',
      },
      {
        city: 'Bled',
        country: 'Slovenia',
        flag: 'si',
        airportCode: 'LJU',
        hotelNightEstimate: 85,
        foodPerDay: 45,
        transportPerDay: 18,
        activityPerDay: 55,
        costLevel: 'mid',
        description: 'Via ferrata, canyoning and lake swimming',
      },
      {
        city: 'Innsbruck',
        country: 'Austria',
        flag: 'at',
        airportCode: 'INN',
        hotelNightEstimate: 95,
        foodPerDay: 55,
        transportPerDay: 20,
        activityPerDay: 70,
        costLevel: 'mid',
        description: 'Skiing, paragliding and trail running in the Alps',
      },
      {
        city: 'Lanzarote',
        country: 'Spain',
        flag: 'es',
        airportCode: 'ACE',
        hotelNightEstimate: 75,
        foodPerDay: 42,
        transportPerDay: 20,
        activityPerDay: 50,
        costLevel: 'budget',
        description: 'Surfing, cycling and lava field adventures',
      },
      {
        city: 'Galway',
        country: 'Ireland',
        flag: 'ie',
        airportCode: 'ORK',
        hotelNightEstimate: 90,
        foodPerDay: 55,
        transportPerDay: 20,
        activityPerDay: 45,
        costLevel: 'mid',
        description: 'Wild Atlantic Way — surfing, hiking, sea kayaking',
      },
      {
        city: 'Bansko',
        country: 'Bulgaria',
        flag: 'bg',
        airportCode: 'SOF',
        hotelNightEstimate: 55,
        foodPerDay: 28,
        transportPerDay: 12,
        activityPerDay: 45,
        costLevel: 'budget',
        description: 'Affordable ski resort with great mountain biking',
      },
      {
        city: 'Tarifa',
        country: 'Spain',
        flag: 'es',
        airportCode: 'TFN',
        hotelNightEstimate: 70,
        foodPerDay: 38,
        transportPerDay: 15,
        activityPerDay: 60,
        costLevel: 'budget',
        description: 'Kitesurfing and windsurfing capital of Europe',
      },
      {
        city: 'Kathmandu',
        country: 'Nepal',
        flag: 'np',
        airportCode: 'KTM',
        hotelNightEstimate: 30,
        foodPerDay: 15,
        transportPerDay: 10,
        activityPerDay: 60,
        costLevel: 'budget',
        description: 'Base camp treks, white water rafting and paragliding',
      },
      {
        city: 'Costa Rica',
        country: 'Costa Rica',
        flag: 'cr',
        airportCode: 'SJO',
        hotelNightEstimate: 65,
        foodPerDay: 28,
        transportPerDay: 20,
        activityPerDay: 70,
        costLevel: 'mid',
        description: 'Zip-lining, surfing, volcano hikes and jungle canopy',
      },
      {
        city: 'Patagonia',
        country: 'Chile',
        flag: 'cl',
        airportCode: 'PUQ',
        hotelNightEstimate: 90,
        foodPerDay: 40,
        transportPerDay: 35,
        activityPerDay: 80,
        costLevel: 'mid',
        description: 'Torres del Paine trekking and glacial adventures',
      },
      {
        city: 'Bali',
        country: 'Indonesia',
        flag: 'id',
        airportCode: 'DPS',
        hotelNightEstimate: 45,
        foodPerDay: 20,
        transportPerDay: 12,
        activityPerDay: 50,
        costLevel: 'budget',
        description: 'Surfing, volcano hiking, white water rafting and diving',
      },
      {
        city: 'Hokkaido',
        country: 'Japan',
        flag: 'jp',
        airportCode: 'CTS',
        hotelNightEstimate: 90,
        foodPerDay: 40,
        transportPerDay: 20,
        activityPerDay: 70,
        costLevel: 'mid',
        description: 'World-class powder skiing and summer cycling routes',
      },
      {
        city: 'Namibia',
        country: 'Namibia',
        flag: 'na',
        airportCode: 'WDH',
        hotelNightEstimate: 80,
        foodPerDay: 30,
        transportPerDay: 40,
        activityPerDay: 70,
        costLevel: 'mid',
        description: 'Dune sandboarding, desert hiking and safari',
      },
      {
        city: 'Medellín',
        country: 'Colombia',
        flag: 'co',
        airportCode: 'MDE',
        hotelNightEstimate: 40,
        foodPerDay: 18,
        transportPerDay: 8,
        activityPerDay: 45,
        costLevel: 'budget',
        description: 'Paragliding over the Andes and coffee region treks',
      },
      {
        city: 'Oman',
        country: 'Oman',
        flag: 'om',
        airportCode: 'MCT',
        hotelNightEstimate: 75,
        foodPerDay: 30,
        transportPerDay: 25,
        activityPerDay: 55,
        costLevel: 'mid',
        description: 'Wadi hiking, dune bashing and diving in pristine reefs',
      },
      {
        city: 'Iceland Ring Road',
        country: 'Iceland',
        flag: 'is',
        airportCode: 'KEF',
        hotelNightEstimate: 130,
        foodPerDay: 65,
        transportPerDay: 70,
        activityPerDay: 80,
        costLevel: 'premium',
        description: 'Epic road trip past waterfalls, glaciers and hot springs',
      },
      {
        city: 'Sri Lanka',
        country: 'Sri Lanka',
        flag: 'lk',
        airportCode: 'CMB',
        hotelNightEstimate: 40,
        foodPerDay: 15,
        transportPerDay: 12,
        activityPerDay: 35,
        costLevel: 'budget',
        description: 'Surfing, tea country trekking and whale watching',
      },
    ],
  },
];
